### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [byt3bl33d3r/pth-toolkit#1]
Do you mind if we add this to the archassault repos? It'd be nice if it could have a license, we have been working on this one for a while.

Thanks

**Comment by archey** [comment]
We would be happy to help with the cross compiling as we compile on i686, x86_64, armv6h and armv7h. If you would like the help.

**Comment by byt3bl33d3r** [comment]
@archey awesome ! big fan of archassault btw! would a BSD license be okay?

**Comment by byt3bl33d3r** [comment]
@archey also help with compiling would be more than welcomed :P

**Comment by archey** [comment]
Sure sounds good to us, just make sure to include the license file so we can add it. Oh and thanks for the kudos, we do our best to pull in the latest mitmf as fast as we can. We compile on real arm hardware so its alot more stable then cross compiling, if you want some real help feel free to stop by freenode #ArchAssault and we can talk more

**Comment by archey** [comment]
Did you compile it all from src or build  a pkgbuild? I only ask as we have a split pkgbuild that builds all of it, but its not working correctly so we haven't made it available yet

**Comment by byt3bl33d3r** [comment]
I actually did neither! this is basically a mish mosh of the original repo plus some stolen libraries and files from kali!

**Comment by byt3bl33d3r** [comment]
never could get the damn thing to compile!

**Comment by archey** [comment]
yeah we did a bit of that as well, we got it to compile. Its just winexe fails with busted symbols Could not find symbol E_md4hash

Using the basic setup from kali's git repo, you should hop online if you want and we can talk about it more
