### ISSUE TITLE
smbget and smbclient don't work on Debian Wheezy

### ISSUE THREAD

**Issue by theguly** [byt3bl33d3r/pth-toolkit#2]
executing bin in rootdir:
bin/net: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by lib/libbsd.so.0)
bin/rpcclient: /lib/x86_64-linux-gnu/libc.so.6: version`GLIBC_2.14' not found (required by lib/libbsd.so.0)
bin/smbclient: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by lib/libbsd.so.0)
bin/smbget: /lib/x86_64-linux-gnu/libc.so.6: version`GLIBC_2.14' not found (required by lib/libbsd.so.0)
bin/winexe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by lib/libbsd.so.0)

debian 7.8 ships with libc 2.13

executing bin in bin/ dir:
./net: error while loading shared libraries: libkrb5-samba4.so.26: cannot open shared object file: No such file or directory
./smbclient: error while loading shared libraries: libpopt_samba3.so: cannot open shared object file: No such file or directory
./smbget: error while loading shared libraries: libuid_wrapper.so: cannot open shared object file: No such file or directory

cannot find this .so in standard debian repo.

resolution like "i don't support debian" is accepted :)

thanks

**Comment by byt3bl33d3r** [comment]
just making sure but you are running the sh scripts and not the actual binaries right?

**Comment by theguly** [comment]
first chunk of errors came from scripts in  ~/pth-toolkit/
for example, ~/pth-toolkit/pth-net, the shell script

second chunk is from script in ~/pth-toolkit/bin
for example ~/pth-toolkit/bin/net

I can provide a script(1) logfile if it helps

**Comment by byt3bl33d3r** [comment]
sure that would be great

**Comment by theguly** [comment]
http://pastebin.com/Mi6k769k

**Comment by byt3bl33d3r** [comment]
@theguly your running debian with the standard kernel and repos?

**Comment by theguly** [comment]
yessir

**Comment by byt3bl33d3r** [comment]
@theguly ok will fire up a vm later today .. i should probably be able to get this working for ya

**Comment by byt3bl33d3r** [comment]
@theguly just a quick update: ive manged to get winexe, wmis, and wmic working on debian , the rest of the utilities will be trickier but ill keep trying.

The problem is that debian wheezy ships with `libc` 2.13 and the utilities require > 2.14

**Comment by byt3bl33d3r** [comment]
as soon as i get all of them working i'll update the repo

**Comment by theguly** [comment]
thanks :)
hope i'm not the only one who use debian...

**Comment by byt3bl33d3r** [comment]
@theguly ideally i would want this to work on every possible *nix system so doesn't really matter what distro your running

**Comment by byt3bl33d3r** [comment]
hey @theguly i created a branch called debian-fix with the changes.. still haven't managed to get the smb related utilities working but as i said wmic, wmis and winexe work
